// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgWU6wEmjDYWuXAZdjl3vmdKM4n7OGUu0',
    appId: '1:728474781417:web:ec4099b9173e7053db1278',
    messagingSenderId: '728474781417',
    projectId: 'spoileralert-2ce64',
    authDomain: 'spoileralert-2ce64.firebaseapp.com',
    databaseURL: 'https://spoileralert-2ce64-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spoileralert-2ce64.appspot.com',
    measurementId: 'G-CHEXZBZ69D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkq6_z_wEc_WLXX7v51VpHvSCYWGYlwbQ',
    appId: '1:728474781417:android:c1dc7b792a6f976fdb1278',
    messagingSenderId: '728474781417',
    projectId: 'spoileralert-2ce64',
    databaseURL: 'https://spoileralert-2ce64-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spoileralert-2ce64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj3eJMNXegRf34TrA1UhmOEBqnlptoD9o',
    appId: '1:728474781417:ios:a5d360a94d41357edb1278',
    messagingSenderId: '728474781417',
    projectId: 'spoileralert-2ce64',
    databaseURL: 'https://spoileralert-2ce64-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spoileralert-2ce64.appspot.com',
    iosBundleId: 'com.example.spoilerAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj3eJMNXegRf34TrA1UhmOEBqnlptoD9o',
    appId: '1:728474781417:ios:228a679a2a6bb7d8db1278',
    messagingSenderId: '728474781417',
    projectId: 'spoileralert-2ce64',
    databaseURL: 'https://spoileralert-2ce64-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spoileralert-2ce64.appspot.com',
    iosBundleId: 'com.example.spoilerAlert.RunnerTests',
  );
}
